# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ActiveRecord::Base.transaction do
  User.destroy_all
  user1 = User.create!(username: "Brenda")
  user2 = User.create!(username: "Kevin")
  user3 = User.create!(username: "Ramsay")
  user4 = User.create!(username: "Karen")
  user5 = User.create!(username: "Eliza")
  user6 = User.create!(username: "Beth")
  user7 = User.create!(username: "George")
  user8 = User.create!(username: "Paul")
  user9 = User.create!(username: "Stacey")
  user10 = User.create!(username: "Brent")

  Artwork.destroy_all
  a1 = Artwork.create!(title: "Big Bird", image_url: "getart.com/big_bird", artist_id: user1.id, favorite: true)
  a2 = Artwork.create!(title: "Sail Away", image_url: "getart.com/sail_away", artist_id: user1.id)
  a3 = Artwork.create!(title: "Dog Pond", image_url: "artguy.com/dog_pond", artist_id: user1.id, favorite: true)
  a4 = Artwork.create!(title: "Diglet", image_url: "getart.com/pokemon/diglet", artist_id: user2.id, favorite: true)
  a5 = Artwork.create!(title: "Spaces", image_url: "getart.com/spaces", artist_id: user4.id)
  a6 = Artwork.create!(title: "Regional Carnage", image_url: "bigideas.com/carnage", artist_id: user5.id, favorite: true)
  a7 = Artwork.create!(title: "Con Artist", image_url: "artguy.com/con-artist", artist_id: user6.id)
  a8 = Artwork.create!(title: "Washed Up Walkman", image_url: "getart.com/washed_up", artist_id: user7.id, favorite: true)
  a9 = Artwork.create!(title: "Trees in Winter Sun", image_url: "getart.com/landscape/tree", artist_id: user8.id, favorite: true)
  a10 = Artwork.create!(title: "Wrong Way Jackson", image_url: "artsy.com/Jack", artist_id: user8.id, favorite: true)

  Collection.destroy_all
  col1 = Collection.create!(name: "Cool Pics", user_id: user1.id)
  col2 = Collection.create!(name: "Nice Art", user_id: user1.id)
  col3 = Collection.create!(name: "Groovy", user_id: user2.id)
  col4 = Collection.create!(name: "Crazy Art", user_id: user2.id)
  col5 = Collection.create!(name: "WOW!", user_id: user4.id)
  col6 = Collection.create!(name: "Fam Pics", user_id: user8.id)
  col7 = Collection.create!(name: "My Favorite Art", user_id: user3.id)
  col8 = Collection.create!(name: "Art Attack!", user_id: user5.id)

  ArtworkCollection.destroy_all
  ac1 = ArtworkCollection.create!(artwork_id: a1.id, collection_id: col1.id)
  ac2 = ArtworkCollection.create!(artwork_id: a2.id, collection_id: col1.id)
  ac3 = ArtworkCollection.create!(artwork_id: a10.id, collection_id: col1.id)
  ac4 = ArtworkCollection.create!(artwork_id: a5.id, collection_id: col2.id)
  ac5 = ArtworkCollection.create!(artwork_id: a3.id, collection_id: col2.id)
  ac6 = ArtworkCollection.create!(artwork_id: a1.id, collection_id: col2.id)
  ac7 = ArtworkCollection.create!(artwork_id: a9.id, collection_id: col2.id)
  ac8 = ArtworkCollection.create!(artwork_id: a8.id, collection_id: col3.id)
  ac9 = ArtworkCollection.create!(artwork_id: a7.id, collection_id: col3.id)
  ac10 = ArtworkCollection.create!(artwork_id: a6.id, collection_id: col3.id)
  ac11 = ArtworkCollection.create!(artwork_id: a5.id, collection_id: col4.id)
  ac12 = ArtworkCollection.create!(artwork_id: a4.id, collection_id: col4.id)
  ac13 = ArtworkCollection.create!(artwork_id: a3.id, collection_id: col5.id)
  ac14 = ArtworkCollection.create!(artwork_id: a2.id, collection_id: col5.id)
  ac15 = ArtworkCollection.create!(artwork_id: a1.id, collection_id: col5.id)
  ac16 = ArtworkCollection.create!(artwork_id: a10.id, collection_id: col5.id)
  ac17 = ArtworkCollection.create!(artwork_id: a6.id, collection_id: col5.id)
  ac18 = ArtworkCollection.create!(artwork_id: a5.id, collection_id: col6.id)
  ac19 = ArtworkCollection.create!(artwork_id: a4.id, collection_id: col6.id)
  ac20 = ArtworkCollection.create!(artwork_id: a6.id, collection_id: col6.id)
  ac21 = ArtworkCollection.create!(artwork_id: a7.id, collection_id: col6.id)
  ac22 = ArtworkCollection.create!(artwork_id: a8.id, collection_id: col7.id)
  ac23 = ArtworkCollection.create!(artwork_id: a9.id, collection_id: col8.id)
  ac24 = ArtworkCollection.create!(artwork_id: a8.id, collection_id: col8.id)

  ArtworkShare.destroy_all
  as1 = ArtworkShare.create!(user_id: user10.id, artwork_id: a3.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user9.id, artwork_id: a3.id)
  as1 = ArtworkShare.create!(user_id: user1.id, artwork_id: a3.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user4.id, artwork_id: a3.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user7.id, artwork_id: a3.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user3.id, artwork_id: a4.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user2.id, artwork_id: a1.id)
  as1 = ArtworkShare.create!(user_id: user1.id, artwork_id: a2.id)
  as1 = ArtworkShare.create!(user_id: user5.id, artwork_id: a5.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user1.id, artwork_id: a6.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user9.id, artwork_id: a7.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user2.id, artwork_id: a8.id)
  as1 = ArtworkShare.create!(user_id: user3.id, artwork_id: a9.id)
  as1 = ArtworkShare.create!(user_id: user8.id, artwork_id: a10.id)
  as1 = ArtworkShare.create!(user_id: user9.id, artwork_id: a10.id)
  as1 = ArtworkShare.create!(user_id: user6.id, artwork_id: a9.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user1.id, artwork_id: a8.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user2.id, artwork_id: a5.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user3.id, artwork_id: a8.id)
  as1 = ArtworkShare.create!(user_id: user3.id, artwork_id: a7.id)
  as1 = ArtworkShare.create!(user_id: user10.id, artwork_id: a6.id)
  as1 = ArtworkShare.create!(user_id: user10.id, artwork_id: a2.id)
  as1 = ArtworkShare.create!(user_id: user9.id, artwork_id: a2.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user5.id, artwork_id: a1.id, favorite: true)
  as1 = ArtworkShare.create!(user_id: user4.id, artwork_id: a1.id, favorite: true)

  Comment.destroy_all

  com1 = Comment.create!(user_id: user1.id, artwork_id: a1.id, body: "Cool art dude!")
  com2 = Comment.create!(user_id: user2.id, artwork_id: a1.id, body: "I Really like this piece")
  com3 = Comment.create!(user_id: user3.id, artwork_id: a2.id, body: "Wow, outt this world!")
  com4 = Comment.create!(user_id: user4.id, artwork_id: a3.id, body: "This is pretty neat")
  com5 = Comment.create!(user_id: user5.id, artwork_id: a4.id, body: "Put a bird on it!")
  com6 = Comment.create!(user_id: user6.id, artwork_id: a5.id, body: "Howe much does this cost?")
  com7 = Comment.create!(user_id: user7.id, artwork_id: a6.id, body: "WIll you be making any prints?")
  com8 = Comment.create!(user_id: user8.id, artwork_id: a7.id, body: "How did you learn how to do this?")
  com9 = Comment.create!(user_id: user9.id, artwork_id: a8.id, body: "Great work sonny jim!")
  com0 = Comment.create!(user_id: user10.id, artwork_id: a10.id, body: "Proud of you son!")
  com1 = Comment.create!(user_id: user1.id, artwork_id: a9.id, body: "Getting really good")
  com2 = Comment.create!(user_id: user2.id, artwork_id: a3.id, body: "The colors reallly pop on this one")
  com3 = Comment.create!(user_id: user5.id, artwork_id: a4.id, body: "Might be my fav!")
  com4 = Comment.create!(user_id: user6.id, artwork_id: a5.id, body: "This one is one of your best yet!")
  com5 = Comment.create!(user_id: user7.id, artwork_id: a8.id, body: "Can you teach me?")

  Like.destroy_all
  l1 = Like.create!(user_id: user1.id, imageable_type: "Comment", imageable_id: 1)
  l2 = Like.create!(user_id: user1.id, imageable_type: "Artwork", imageable_id: 2)
  l3 = Like.create!(user_id: user2.id, imageable_type: "Comment", imageable_id: 1)
  l4 = Like.create!(user_id: user2.id, imageable_type: "Artwork", imageable_id: 3)
  l5 = Like.create!(user_id: user3.id, imageable_type: "Comment", imageable_id: 4)
  l6 = Like.create!(user_id: user4.id, imageable_type: "Artwork", imageable_id: 5)
  l7 = Like.create!(user_id: user5.id, imageable_type: "Comment", imageable_id: 6)
  l8 = Like.create!(user_id: user6.id, imageable_type: "Comment", imageable_id: 7)
  l9 = Like.create!(user_id: user6.id, imageable_type: "Artwork", imageable_id: 8)
  l10 = Like.create!(user_id: user7.id, imageable_type: "Artwork", imageable_id: 7)
  l11 = Like.create!(user_id: user8.id, imageable_type: "Comment", imageable_id: 9)
  l12 = Like.create!(user_id: user9.id, imageable_type: "Artwork", imageable_id: 10)
  l13 = Like.create!(user_id: user10.id, imageable_type: "Comment", imageable_id: 1)
  l14 = Like.create!(user_id: user5.id, imageable_type: "Artwork", imageable_id: 3)
  l15 = Like.create!(user_id: user9.id, imageable_type: "Artwork", imageable_id: 4)
end
